# Generated by Django 5.2.3 on 2025-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skills_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
