# Generated by Django 5.2.3 on 2025-06-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about_skills_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skills_intro',
        ),
    ]
