# Generated by Django 5.2.3 on 2025-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_about_skills_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Skills Intro Text')),
            ],
        ),
    ]
