# Generated by Django 5.2.3 on 2025-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_skillsintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True, verbose_name='Introductory Text for Skills Section')),
            ],
        ),
        migrations.DeleteModel(
            name='SkillsIntro',
        ),
    ]
