# Generated by Django 5.2.3 on 2025-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_skillssection_delete_skillsintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillssection',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='Skills Intro Text'),
        ),
    ]
