# Generated by Django 5.2.3 on 2025-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_skillssection_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillssection',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='Intro Text for Skills'),
        ),
    ]
