# Generated by Django 5.2.3 on 2025-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_skillssection_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_intro',
            field=models.BooleanField(default=False),
        ),
    ]
