# Generated by Django 5.2.3 on 2025-06-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_skill_intro_text_skill_is_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_intro',
        ),
    ]
