# Generated by Django 5.2.3 on 2025-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_skill_intro_text_remove_skill_is_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
