# Generated by Django 5.2.3 on 2025-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_skillssectioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillssectioncontent',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
