# Generated by Django 5.2.3 on 2025-06-11 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_about_is_html_skillssectioncontent_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='skillssectioncontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
