# Generated by Django 5.2.3 on 2025-06-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_about_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='skillssectioncontent',
            name='is_html',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(help_text='You can enter plain text or HTML. HTML will be rendered as HTML.'),
        ),
        migrations.AlterField(
            model_name='skillssectioncontent',
            name='content',
            field=models.TextField(help_text='You can enter plain text or HTML. HTML will be rendered as HTML.'),
        ),
    ]
