# Generated by Django 5.2.3 on 2025-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_projectitem_delete_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
