# Generated by Django 5.2.3 on 2025-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_projectitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
