# Generated by Django 5.2.3 on 2025-06-20 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_projectitem_image_alter_projectitem_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 20)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='description',
            field=models.TextField(),
        ),
    ]
