# Generated by Django 5.2.3 on 2025-06-20 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_galleryimage_options_alter_projectitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
