# Generated by Django 5.2.3 on 2025-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_skillitem_delete_skill_delete_skillssection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('website', 'Website')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
