# Generated by Django 5.2.3 on 2025-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('email', 'Email'), ('website', 'Website')], max_length=50),
        ),
    ]
