# Generated by Django 5.2.3 on 2025-06-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('content', 'Content Section'), ('gallery', 'Gallery Section'), ('skills', 'Skills Section'), ('projects', 'Projects Section'), ('about', 'About Section')], max_length=20),
        ),
    ]
