# Generated by Django 5.2.3 on 2025-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_section_image_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('content', 'Content Section'), ('gallery', 'Gallery Section'), ('skills', 'Skills Section'), ('projects', 'Projects Section')], max_length=20),
        ),
    ]
