# Generated by Django 5.2.3 on 2025-06-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
